Add deployment rollback option

diff --git a/bin/k8s-verify-deployment b/bin/k8s-verify-deployment
--- a/bin/k8s-verify-deployment
+++ b/bin/k8s-verify-deployment
@@ -9,16 +9,23 @@ do
   echo "Checking deployment for $DEPLOYMENT"
   timeout.sh -t ${DEPLOY_TIMEOUT} verify-deployment $DEPLOYMENT $NAMESPACE
   result=$?
-  if [ "$result" == "143" ] ; then
-      echo "------- DEPLOYMENT TIMEOUT FAIL --------"
-      exit 1
-  fi
+  
   if [ "$result" == "0" ] ; then
     echo "DEPLOY SUCCESFUL"
+  elif [ "$result" == "143" ] ; then
+    echo "------- DEPLOYMENT TIMEOUT FAIL --------"
+    if [[ -z "${ROK8S_ROLLBACK_DEPLOYMENTS}" ]]; then
+      rollback-deployment $DEPLOYMENT $NAMESPACE
+    fi
+    exit 1
   else
     echo "DEPLOY FAILED"
+    if [[ -z "${ROK8S_ROLLBACK_DEPLOYMENTS}" ]]; then
+      rollback-deployment $DEPLOYMENT $NAMESPACE
+    fi
     exit $result
   fi
+
 done
 
 echo "All objects created"
