Attempting to maintain backwards compatibility while allowing the intent of the script to use a default config file when a specific file is passed in, and the default exists but not use the default file when a config file is passed in fixes #47

diff --git a/bin/k8s-read-config b/bin/k8s-read-config
--- a/bin/k8s-read-config
+++ b/bin/k8s-read-config
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+DEFAULT_CONFIG_FILE="deploy/k8s-scripts.config"
+
 if [ -n "${CONFIG_READ+1}" ]
 then
   echo "Config already read"
@@ -24,13 +26,17 @@ BASEDIR=$(pwd)
 DEPLOY_TIMEOUT=${DEPLOY_TIMEOUT:-300}
 BLOCKING_JOB_TIMEOUT=${BLOCKING_JOB_TIMEOUT:-300}
 
-CONFIG=${CONFIG_FILE:-deploy/k8s-scripts.config}
-if test -f $BASEDIR/$CONFIG ; then
-  echo "Loading configuration from ${BASEDIR}/$CONFIG"
-  . $BASEDIR/$CONFIG
+if test -z $CONFIG_FILE && test -f $BASEDIR/$DEFAULT_CONFIG_FILE ; then
+  echo "Loading configuration from ${BASEDIR}/$DEFAULT_CONFIG_FILE"
+  . $BASEDIR/$DEFAULT_CONFIG_FILE
 else
-  echo "Config file, ${BASEDIR}/$CONFIG, not found." >&2
-  exit 1
+  if test -f $BASEDIR/$CONFIG_FILE ; then
+    echo "Loading configuration from ${BASEDIR}/$CONFIG_FILE"
+    . $BASEDIR/$CONFIG_FILE
+  else
+    echo "Config file, ${BASEDIR}/$CONFIG_FILE, not found." >&2
+    exit 1
+  fi
 fi
 
 echo "[dockerfile]: $DOCKERFILE"
