adding scripts to shellcheck, moving lines in package.json, adding logical checks in prepare-gcloud

diff --git a/bin/prepare-gcloud b/bin/prepare-gcloud
--- a/bin/prepare-gcloud
+++ b/bin/prepare-gcloud
@@ -1,8 +1,13 @@
 #!/bin/bash -e
 echo "Preparing the gcloud command line tools."
 
-if [[ -z "$GCP_PROJECT"  ]]; then
-  echo "Missing GCP project, or zone!  Aborting"
+if [[ -z ${GCP_PROJECT+x}  ]]; then
+  echo "Missing GCP_PROJECT environment variable.  Aborting"
+  exit 1
+fi
+
+if [[ -z ${GCLOUD_KEY+x}  ]]; then
+  echo "Missing GCLOUD_KEY environment variable.  Aborting"
   exit 1
 fi
 
diff --git a/bin/prepare-kubectl b/bin/prepare-kubectl
--- a/bin/prepare-kubectl
+++ b/bin/prepare-kubectl
@@ -7,5 +7,11 @@ if [ -n "$KUBECONFIG_DATA" ]; then
   echo "${KUBECONFIG_DATA}" | base64 --decode > ~/.kube/config
 else
   cloud-login
-  gcloud container clusters get-credentials "${CLUSTER_NAME}" --zone "${GCP_ZONE}" --project "${GCP_PROJECT}"
+  if [ -n "${CLOUD_LOGGED_IN+1}" ]
+  then
+    gcloud container clusters get-credentials "${CLUSTER_NAME}" --zone "${GCP_ZONE}" --project "${GCP_PROJECT}"  
+  else
+    echo "Unable prepare kubectl. No KUBECONFIG_DATA or no GCP login provided."
+    exit 1
+  fi
 fi
