standardize base_dir concept in k8s-run-blocking-job

diff --git a/bin/run-blocking-job b/bin/run-blocking-job
--- a/bin/run-blocking-job
+++ b/bin/run-blocking-job
@@ -2,7 +2,7 @@
 
 # Runs a Kubernetes Job once. Designed for a single, non-parallel job, typically db migrations
 # http://kubernetes.io/docs/user-guide/jobs/#parallel-jobs
-# The job needs to be located in KUBERNETES_CONFIG_PATH, named ${JOB_NAME}.job.yml,
+# The job needs to be located in $BASEDIR/deploy, named ${JOB_NAME}.job.yml,
 # and JOB_NAME should match the job's metadata.name attribute
 # Usage: ./script/run-migrations.sh JOB_NAME
 
@@ -12,7 +12,15 @@ then
   exit 1
 fi
 
+if [ -z "$1" ]
+then
+  echo "ERROR: No Job specified"
+  exit 1
+fi
+
 JOB_NAME="$1"
+NAMESPACE=${2:=default}
+
 POLL_TRIES=${POLL_TRIES:-30}
 POLL_WAIT=${POLL_WAIT:-10}
 
