add yq to ci-images (#390)
* add yq

* update docker to 20

* install yq via install script

* better error handling on orb vault commands. Fix install script

* idk

* apparently there are two spaceS

diff --git a/orb/commands/get_vault_env.yml b/orb/commands/get_vault_env.yml
--- a/orb/commands/get_vault_env.yml
+++ b/orb/commands/get_vault_env.yml
@@ -13,6 +13,8 @@ steps:
       command: |
         vault token lookup >/dev/null 2>&1
         if [ $? != 0 ]; then echo "Vault token expired or not available!" && exit 1; fi
+        vault kv get -format=yaml << parameters.vault_path >> 2>&1
+        if [ $? != 0 ]; then echo "Cannot read vault path << parameters.vault_path >>" && exit 2; fi
         set -e
         envData=$(vault kv get -format=yaml << parameters.vault_path >> | yq r - data.data | sed -nr 's/([A-Z_]+): (.*)/\1=\2/ p')
         for i in "${envData[@]}"; do echo "export $i" >> ${BASH_ENV}; done
